### ISSUE TITLE
problem with test_template.xml

### ISSUE THREAD

**Issue by jeromecc** [ppazos/cabolabs-emrapp#52]
The processing instruction target matching "[xX][mM][lL]" is not allowed.	test_template.xml	/cabolabs-emrapp	line 3072	XML Problem

I guess Eclipse doesn't like the xml prolog inside the xml document...

**Comment by ppazos** [comment]
@jeromecc I would need the XML.

**Comment by jeromecc** [comment]
You already have it. It's cabolabs-emrapp/test_template.xml ;-)
